package util;

public enum View {
	HOME,
	ADMIN, ADMIN_LOGIN, ADMIN_BOARD_LIST,
	MEMBER,MEMBER_LOGIN, MEMBER_LOGIN_AFTER, MEMBER_JOIN, MEMBER_MYBOARD_SHOW, 
	MEMBER_MYBOARD_UPDATE, MEMBER_BOARD_UPDATE_BEFORE, MEMBER_BOARD_UPDATE_CHECK, MEMBER_BOARD_UPDATE_SHOW,
	MEMBER_BOARD_LIST, MEMBER_BOARD_LIST_ALL, MEMBER_BOARD_DETAIL, MEMBER_BOARD_INSERT,	BOARD_UPDATE , BOARD_DELETE,
	BOARD_BAN_SELECT, BOARD_BAN_LIST, BOARD_BAN_UPDATE, BOARD_BAN_DETAIL
	
}
